export default {
  name: 'siteSettings',
  title: 'サイト設定',
  type: 'document',
  __experimental_actions: ['update', 'publish'],
  groups: [
    { name: 'nav', title: 'ナビゲーション' },
    { name: 'hero', title: 'ヒーロー' },
    { name: 'ticker', title: 'ティッカー' },
    { name: 'products', title: '商品セクション' },
    { name: 'community', title: 'コミュニティ' },
    { name: 'footer', title: 'フッター' },
  ],
  fields: [
    // ナビ
    {
      name: 'navLogo',
      title: 'ナビ：ロゴテキスト',
      type: 'string',
      group: 'nav',
      description: '例: httk',
    },
    // ヒーロー
    {
      name: 'heroEyebrow',
      title: 'ヒーロー：小見出し',
      type: 'string',
      group: 'hero',
      description: '例: secret code for office workers',
    },
    {
      name: 'heroTitle',
      title: 'ヒーロー：メインタイトル',
      type: 'string',
      group: 'hero',
      description: '例: httk（大きく表示される文字）',
    },
    {
      name: 'heroSub',
      title: 'ヒーロー：サブタイトル（強調部分）',
      type: 'string',
      group: 'hero',
      description: '例: 本当は定時で帰りたい',
    },
    {
      name: 'heroSubSuffix',
      title: 'ヒーロー：サブタイトル（後半）',
      type: 'string',
      group: 'hero',
      description: '例: — でも言えない、全員の本音',
    },
    {
      name: 'heroCta1',
      title: 'ヒーロー：ボタン1テキスト',
      type: 'string',
      group: 'hero',
      description: '例: アイテムを見る',
    },
    {
      name: 'heroCta2',
      title: 'ヒーロー：ボタン2テキスト',
      type: 'string',
      group: 'hero',
      description: '例: httkとは？',
    },
    // ティッカー
    {
      name: 'ticker',
      title: 'ティッカー（流れるテキスト）',
      type: 'array',
      group: 'ticker',
      of: [{ type: 'string' }],
      description: '流れるテキストのリスト',
    },
    // 商品セクション
    {
      name: 'productsSectionLabel',
      title: '商品セクション：ラベル',
      type: 'string',
      group: 'products',
      description: '例: items',
    },
    {
      name: 'productsSectionTitle',
      title: '商品セクション：タイトル',
      type: 'string',
      group: 'products',
      description: '例: 同志の証を\n身につけろ（改行は\\nで）',
    },
    {
      name: 'productsCtaText',
      title: '商品セクション：ボタンテキスト',
      type: 'string',
      group: 'products',
      description: '例: 全アイテムを見る',
    },
    // コミュニティ
    {
      name: 'communityEmoji',
      title: 'コミュニティ：絵文字',
      type: 'string',
      group: 'community',
      description: '例: ✊',
    },
    {
      name: 'communityTitle',
      title: 'コミュニティ：タイトル',
      type: 'string',
      group: 'community',
      description: '例: 一人じゃない。\n仲間がいる。',
    },
    {
      name: 'communityBody',
      title: 'コミュニティ：本文',
      type: 'text',
      group: 'community',
      rows: 3,
    },
    {
      name: 'communityHashtag',
      title: 'コミュニティ：ハッシュタグ',
      type: 'string',
      group: 'community',
      description: '例: #httk',
    },
    {
      name: 'communityCta',
      title: 'コミュニティ：ボタンテキスト',
      type: 'string',
      group: 'community',
      description: '例: 今日から仲間になる',
    },
    // フッター
    {
      name: 'footerLogo',
      title: 'フッター：ロゴテキスト',
      type: 'string',
      group: 'footer',
      description: '例: httk',
    },
    {
      name: 'footerTagline',
      title: 'フッター：タグライン',
      type: 'string',
      group: 'footer',
      description: '例: 本当は定時で帰りたい — みんなで帰れば恐くない',
    },
    {
      name: 'footerCopyright',
      title: 'フッター：コピーライト',
      type: 'string',
      group: 'footer',
      description: '例: © 2026 httk. All rights reserved.',
    },
  ],
}
